### ISSUE TITLE
Provide "explanatory features" from model

### ISSUE THREAD

**Issue by bpben** [insight-lane/crash-model#103]
One of the goals of the project is to provide actionable insight to stakeholders.  One way we can do that even with the model we have now is listing some of the high importantance/high magnitude features.  Some thinking needs to be done about what's the best way to do this and what it might produce.

**Comment by bpben** [comment]
Right now I'm just going to output features, generally and we can do whatever aggregations we want.  I think it might make sense to add some "importance" score to them rather then just have them all out there. 

For v2, we need to think of the best way to include these.  It may make sense to have the model output its coefficients or importance scores, but then we need some method for incorporating them.

@terryf82 @alicefeng what are your thoughts?

**Comment by alicefeng** [comment]
Yeah, just outputting the values of the features doesn't seem like it would offer much in the way of "insight" unless planners have such a difficult time looking up the attributes of the roads in their own internal systems.  

Agreed that we need further discussion of how to incorporate coefficients or importance scores in v2.  @bpben  How granular can we get with the interpretability?

**Comment by bpben** [comment]
What do you mean by granular? With regression-type models we should get actual relationship magnitudes (e.g. relation between speed and risk), though sklearn isn't really built for that kind of analysis.  With RF/XGboost there's some loose interpretability you can add on with stuff like [LIME](https://github.com/marcotcr/lime) and [Shapely](https://github.com/slundberg/shap) values.

**Comment by alicefeng** [comment]
I meant if the explanations are for the model as a whole (i.e., these are the most important features across all segments) or for each segment individually (i.e., these are the most important features for this specific segment).  But yeah, also if we can get actual relationship magnitudes (i.e., this is how much speed contributes to risk).

**Comment by bpben** [comment]
Okay! We're re-opening this for 2.1!  I think...

This is basically how we'd determine which features to show on the side panel.  @alicefeng where did we get to with display here? I remember you having some kind of "important feature" display.  But did we end up nixing that? Is there a way we can revisit it?

**Comment by alicefeng** [comment]
Yeah I think I commented out the code I had written to explore this. We can definitely bring this back, the crucial bit here is figuring out how we're passing data on feature importances from the model to the viz.

**Comment by bpben** [comment]
So right now we have feature_importances.json being output to processed https://github.com/Data4Democracy/crash-model/blob/1dc2beecea7903d0b27e1c509b7a5df36ae2baa4/src/models/train_model.py#L43-L53

But I think we'd also need to put some citywide averages in there.

**Comment by alicefeng** [comment]
Yes, we need to add in citywide averages/distributions somewhere. Would this be another file that's separate from preds_final.geojson?

**Comment by alicefeng** [comment]
Oh, another idea we had at one point was letting the most important features drive the map filters. May be worth keeping this in the back of our minds too.

**Comment by bpben** [comment]
I think the averages were one of the things I was outputting with those importances at one point.  Since it's at the feature level, probably makes sense to be a separate file.  What do you think, maybe a json keyed by feature name with "importance" and "average"

I think that makes sense.  We display the most important feature averages and we build a selector for those groupings.

**Comment by bpben** [comment]
I think we have a first cut at this in the showcase, we might want to re-open as we get fresh requests.
