### ISSUE TITLE
Add comments on existing concerns 

### ISSUE THREAD

**Issue by alchenist** [insight-lane/crash-model#12]
Currently, we're only using entries on the [Vision Zero Concerns map](http://app01.cityofboston.gov/VZSafety/); however, there are also [comments on existing entries(https://data.boston.gov/dataset/vision-zero-comment), which are in a slightly different format. We should include these in concerns-based features.

**Comment by bpben** [comment]
Requires some thinking, but not help wanted for now.

**Comment by bpben** [comment]
#318 should allow for customization like this.
