### ISSUE TITLE
Plan next phase of visualization functionality

### ISSUE THREAD

**Issue by terryf82** [insight-lane/crash-model#139]

**Comment by terryf82** [comment]
starting point for discussions provided by @alicefeng here - https://docs.google.com/document/d/1BC_n-cWd1TfCi6ZgWXwptajbURTk7y_rmAzuHp0SGL4/edit

Suggestions can be added to the doc directly and we can use this issue for any discussion required.

**Comment by terryf82** [comment]
@alicefeng great work on this. I've added some ideas and questions for discussion, which we can go through at the next meeting once others have had a chance to review too.

**Comment by alicefeng** [comment]
thanks for adding your thoughts @terryf82 !  a lot of great ideas and suggestions in there.  looking forward to discussing more with the group!

**Comment by alicefeng** [comment]
Mock ups reside here: https://drive.google.com/open?id=13-AO6jJqhV1T62upxT737uPZJ-j0dT_t

**Comment by bpben** [comment]
This is done! Keeping some of the ideas doc for later addition of issues.
