### ISSUE TITLE
Add transit stops as a feature

### ISSUE THREAD

**Issue by j-t-t** [insight-lane/crash-model#190]
Prioritized because it's been requested by Philadelphia stakeholders

**Comment by nsteins** [comment]
Any thoughts or progress on this? I tried adding bus stops via the supplemental csv pattern, but the stops don't have a date associated with them, which I think breaks the functionality. I think we could use the `standardize_point_data.py` script if we are able to skip the date aspect. I just don't know what that would break down the line.

**Comment by j-t-t** [comment]
I think the goal was to use a standardized data source so that adding transit stops wouldn't need to be a one-off for each city. Open Street Maps has some of this data, and there are other transit info data sources that we were hoping to use.

You can certainly add your transit stops as a one off (but I wouldn't close this task if you do) via point-based features. If I recall correctly, the reason date was required was so that if a particular feature didn't exist during a window of dates when you were looking at crashes, it would get filtered out. If you make the changes so that date is not required, and then to test:
- Run the pipeline with the date-free features without limiting the date on crashes and make sure all the features make it in
- Run the pipeline with the date-free features while limiting the dates on crashes and make sure all the features make it in
- Make sure that running the pipeline with dated features on a limited crash date range is consistent in dropping the features with and without your changes.

If I'm not recalling this correctly, let me know and I can dig into it. It would be great to add these checks as unit tests as well. Let me know if I can help.

**Comment by bpben** [comment]
#318 should have unlocked this! @nsteins  - I know this is a blast from the past but if you're interested in contributing here, let me no.  I'm going to close this as it's city-specific and we might need a fresh request to reopen.
