### ISSUE TITLE
Finalize deployment strategy for showcase

### ISSUE THREAD

**Issue by shreyapandit** [insight-lane/crash-model#250]
* We are currently in the midst of discussing and moving from our Docker/Terraform based showcase to hosting our viz as a static site on S3/ Github pages.
*  S3 deployment is done: https://s3.amazonaws.com/crash-model/index.html
* Need to configure github pages, which is a better option.

**Comment by bpben** [comment]
This is part of the website now: https://github.com/insight-lane/insight-lane.github.io

This works, until it doesn't.  Will need to figure out a more appropriate backend here at some point.
