### ISSUE TITLE
input raw crash data file is getting updated with new lines

### ISSUE THREAD

**Issue by piyushm08** [insight-lane/crash-model#265]
input raw crash data file is being updated with newline added to each row after first pipeline.py run.

[Crashes_Last_Five_Years_sampledata_with_newlines_inserted.xlsx](https://github.com/Data4Democracy/crash-model/files/3239368/Crashes_Last_Five_Years_sampledata_with_newlines_inserted.xlsx)

**Comment by bpben** [comment]
Closing this because it's stale, feel free to reopen if you still would like this addressed.
