### ISSUE TITLE
Develop functionality around crash categorization

### ISSUE THREAD

**Issue by j-t-t** [insight-lane/crash-model#49]

**Comment by terryf82** [comment]
The existing crashes standard (https://github.com/Data4Democracy/crash-model/blob/master/standards/crashes-schema.json) includes provision for recording the details of vehicles (by category ["car", "bike", "taxi", "bus", "truck"] and quantity) and persons (by category ["driver", "pedestrian", "cyclist", "other"], quantity and injury severity ["minor", "major", "fatal", "unknown"]) where available.

Standardize_crashes.py is already populating this (lines 65 - 92), using options specified in the city's config file. Where possible it adds quantities of vehicles / persons, but I think only one of the test cities supplied this data (DC if I remember correctly).

Being able to filter crashes by these properties is probably the next step, which might help us understand if the standard needs further development.

**Comment by bpben** [comment]
I'm adding this to 2.1.  I think it sort of captures a new goal of ours: to allow for functionality to split predictions based on a column.  The means that someone can add a feature name to the config yaml file and the model will try and train/predict on the data split by that feature name.  

So for example: If there's a feature that identifies a crash as a vehicle-on-vehicle crash vs a bike-on-vehicle crash, we could specify that in that in the config file and the model will train separate models on vehicle-vehicle crashes vs bike-vehicle crashes.

Does this make sense? @j-t-t @shreyapandit @alicefeng @terryf82 Should we open a different issue?
