### ISSUE TITLE
Features based on nearby land use

### ISSUE THREAD

**Issue by alchenist** [insight-lane/crash-model#5]
It would be interesting to use [open assessing data](https://data.boston.gov/dataset/property-assessment) to generate some basic features based on nearby land use. There's been [some research](https://www.researchgate.net/profile/Joewono_Prasetijo/publication/258167936_Application_of_Adaptive_Neuro-fuzzy_Inference_System_for_road_accident_prediction/links/560b79c008ae576ce6411a9b.pdf) indicating that land use may affect crash risk in a non-urban setting.

**Comment by bpben** [comment]
As part of this see https://github.com/Data4Democracy/boston-crash-modeling/issues/6

**Comment by bpben** [comment]
Incorporating into wishlist: https://docs.google.com/document/d/1cInH_207pvu8fI3J99frYpOi5ZGIT7um4FrxZoh1NIw/edit
