### ISSUE TITLE
Discrepencies between README and Makefile for creating environment

### ISSUE THREAD

**Issue by micahjsmith** [insight-lane/crash-model#57]
Hello!

The README advises creating the development environment using the `environment.yml` file. Meanwhile, the Makefile provides `create_environment` and `requirement` targets that uses a generic conda env and a `pip install -r requirements.txt`. Should the Makefile even be used, or is it unchanged from the cookie cutter template?

Trying `make data` with a fresh clone results in an error
```
ImportError: No module named fiona
```
that seems to result from not using the environment.yml to define the environment and install fiona.

(If it should be supported, I could take a stab at updating the Makefile)

**Comment by j-t-t** [comment]
Hi Micah,

Welcome!  Right now the Makefile is unchanged from the cookie cutter
template, except that make data works.  It certainly would be worth
updating.

Also, feel free to join the slack channel.

Jenny
