### ISSUE TITLE
Look at hosting & deployment options

### ISSUE THREAD

**Issue by terryf82** [insight-lane/crash-model#71]
With development now taking place under Docker, we have lots of options for deployment of the project (e.g AWS, or any other cloud services provider). Domino Datalabs have also shown interest in helping us out with hosting support.

We need to determine what the level of resources required for the pipeline version will be, and come up with a strategy for deployment.

Data storage will also need to be considered into this.

**Comment by bpben** [comment]
Will incorporate into broader deployment milestone.
