### ISSUE TITLE
Look at incorporating "transition features" into segments

### ISSUE THREAD

**Issue by terryf82** [insight-lane/crash-model#76]
Right now our segments taken from OSM ways are linestrings between two termination points (e.g. A and B) which are either endpoints (dead-ends) or intersections. These are extracted using "strict" sampling in OSMNX.

OSM may actually have multiple ways between two termination points, for example the road between A and B may have two ways: one part that has 2 lanes, the other which has 3.

For now we are going to ignore these situations and stick with strict extraction, but in the future it may be worth picking up this type of change and adding it to our segment as a transition feature.

**Comment by terryf82** [comment]
@j-t-t let me know if this summarises the situation or feel free to adjust as needed, thanks.

**Comment by terryf82** [comment]
@j-t-t it's been quite a while since we talked about this, do you think it has a place in 1.2 in terms of effort & pay-off?

**Comment by j-t-t** [comment]
I'm not sure this is worth putting in 1.2, except maybe in creating data standards for it.

**Comment by bpben** [comment]
Closing for now as stale - not quite sure the way to address this.
