### ISSUE TITLE
Features to add to the model

### ISSUE THREAD

**Issue by j-t-t** [insight-lane/crash-model#89]
This is the issue where we track features we want to consider adding.  If we decide to work on these, we can spin them off into tasks
-streetlights
-block size (smaller blocks significantly decrease crash rates per person)
-street trees

**Comment by j-t-t** [comment]
This is just a start, I just threw in things that I got from a quick glance at the presentation. @bpben @alicefeng @andhint @terryf82

**Comment by alicefeng** [comment]
We also have a few lists saved in our google drive:

https://docs.google.com/document/d/1cInH_207pvu8fI3J99frYpOi5ZGIT7um4FrxZoh1NIw/edit?usp=sharing

https://docs.google.com/document/d/1ye4AfAou--cARKrgdcVl_Se8yJD90ctIDEcY-G6DWFo/edit?usp=sharing

**Comment by andhint** [comment]
This is a similar problem (temporal-spatial) that I thought had some interesting features we might be able to pull in.
https://medium.com/data-from-the-trenches/predicting-crime-in-portland-oregon-184453cccd5b

**Comment by j-t-t** [comment]
Also adding link to https://www.dropbox.com/s/xlrnvyjg4fjkb7x/FINAL_PRESENTATION_V4.pdf?dl=0 so it's all in one place

**Comment by bpben** [comment]
Consolidated the wishlist: https://docs.google.com/document/d/1cInH_207pvu8fI3J99frYpOi5ZGIT7um4FrxZoh1NIw/edit

May need prioritization and then adding features as they are available.
