### ISSUE TITLE
Finalize Docker setup to support pipeline process & display of visualization

### ISSUE THREAD

**Issue by terryf82** [insight-lane/crash-model#98]
Ensure the Docker configuration is complete in its support for all required libraries, as well as serving of the visualization.

**Comment by terryf82** [comment]
I'd like to confirm that the Docker image we've built supports all of the pipeline process dependencies, and is able to handle serving of the viz tools.

@bpben I think in the last meeting you mentioned the xgboost library, and that its dependencies may be tricky to satisfy. If I'm able to run the /src/models/train_model.py script, is that a good indication that the environment is sufficient?

@alicefeng for the viz - should historical_crash_map.py be added to the pipeline process? I've setup apache in the Docker image to serve the viz locally, and I assume once this script is run then the html file(s) just load local resources, or is there more to it?

Additionally, I'd also like to understand what the resistance points are in Docker being used consistently while developing the project. I've probably done a bad job of explaining this previously, but the big advantages to using Docker are portability and reproducibility. Especially when we get to the stage of deploying the project into a hosted environment, we want to avoid the "it works on my machine" problem, as well as be able to part out the different parts of the project into containers of single responsibility. If anyone has specific problems with using Docker please post a comment and we can work to resolve them, thanks.

@j-t-t @andhint

**Comment by bpben** [comment]
That's great news! Good to hear it's working.  My sense is that Docker make sense at each checkpoint in the project, but figuring out how to make Docker work on certain elements when it's still unclear whether those elements are going to be in the final product seems like it might be wasted effort.  But I totally agree that making Docker work with the various components of this v1 release makes sense.

**Comment by alicefeng** [comment]
@terryf82 Yes, historical_crash_map.py should be added to the pipeline process.  That script is needed to generate the datasets displayed in the viz.  One other tweak that will need to be implemented is a way for the viz to figure out what city needs to be displayed in the map.  Currently the lat/long is hardcoded so I need to change that to be more flexible.

As for Docker, my only issue with it has been that I keep forgetting what are the commands I need to type to use it. ^_^
